### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by Godswilly**
In this project, we aimed at producing a clone of the New York Times news page, we focused on how to use positioning elements in CSS (flex, grid, float). We tried laying out the basic structure of the page using semantic HTML elements and ensuring that the elements are properly sized and positioned.

### CODE REVIEW

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @Godswilly & @Guy-Gustave  👋 
-
You have done a good job! :tada: Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
## REQUIRED
- [ ] The main image and the rest of the embedded videos are not properly centred as with the source.  See the example difference below 👇 

|[Source](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone](https://raw.githack.com/Guy-Gustave/POSITIONING-AND-FLOATING-ELEMENTS/feature/index.html)|
|:---:|:---:|
|top|top-clone|

- [ ] Improve the styling on the theory of inflation section. Currently, the contents are covering almost 90% of the view width, lets make it more compact by reducing its actual size to match its source. See the difference below 👇 

|[Source](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone](https://raw.githack.com/Guy-Gustave/POSITIONING-AND-FLOATING-ELEMENTS/feature/index.html)|
|:---:|:---:|
|theory|theory-clone|

- [ ] Reduce also, the width of the content to resemble that of the source page. See the difference below 👇 

|[Source](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone](https://raw.githack.com/Guy-Gustave/POSITIONING-AND-FLOATING-ELEMENTS/feature/index.html)|
|:---:|:---:|
|content|content-clone|
 
- [ ] The footer also needs some attention to be paid to it. See the difference below 👇 

|[Source](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone](https://raw.githack.com/Guy-Gustave/POSITIONING-AND-FLOATING-ELEMENTS/feature/index.html)|
|:---:|:---:|
|footer|footer-clone|

- [ ] The clone should have a fixed positioned footer (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html))

- [ ] Make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright). For instance, we the `content-one` class has repeatedly been used all over the stylesheet. It would be great to see all the styling done in one place.

## OPTIONAL
- [ ] Once done with the changes in the CSS and we have ensure it is complying with the rules, I'd advice we validate our CSS with this [tool](https://jigsaw.w3.org/css-validator/validator).

- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by Godswilly** [comment]
I have cross checked my local version of the code it's positioned properly.
I had to effect some changes still and committed it again. Hope it reflects
with the GitHub version.

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hello team :wave:
-
The ☝️  above-highlighted changes have not been addressed with this CCR. I am still seeing exactly what's highlighted in the screenshot. I used a 15" screen view to review this project. Kindly work on those changes, please.
##
Also, for this project to be approved, linter must be enabled and all the checks must be passing. Kindly work on that as well.

- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Review by sumancrest0001 — COMMENTED** [review]
**Status: changes required
Hello TEAM,**
You have done a great job to fix most of the issues raised by the previous TSEs. But there are still a couple of small changes required to get green signal for this project. Let's make the following changes and request another code review.

[REQUIRED] Sticky footer is missing for your project. Please reference the [original page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)

[REQUIRED] More in Space and Astronomy and editor's pick sections should have three articles in a row but in your project, there are two articles per column.
Screenshot from 2020-05-30 15-39-24

**Review by sumancrest0001 — CHANGES_REQUESTED** [review]
Kindly make the above-requested changes and submit the project for another review.

Contact me on slack (Suman Shrestha) if you have any queries regarding the review.
Happy coding !!!

**Comment by Godswilly** [comment]
We have resolved this with the TSE; [REQUIRED] More in Space and Astronomy and editor's pick sections should have three articles in a row but in your project, there are two articles per column.
Below are the screenshots for the proof.
Proof
Proof1
githackproof
githackproof2

**Review by sumancrest0001 — APPROVED** [review]
**STATUS: APPROVED :fire: :clap: 
Congratulation TEAM :100: :+1: , you have done a great job.**
It looks good to me as you implemented the requested changes. Now, you can merge the working branch to master. One optional change though, You can add background color white to the sticky footer instead of transparent. Currently, content from the main page is visible. Have a look :point_down: 
Screenshot from 2020-05-30 21-29-44


**Happy coding !!!**

**Pull request merged**
